spring:
  datasource:
    url: jdbc:mysql://39.107.34.150:3306/mymart?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true

dubbo:
  application:
    name: user-service
    owner: dylan
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://39.107.34.150:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://39.107.34.150:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.dylan.userprovidersss
server:
  port: 8061
logging:
  level:
    com:
      dylan:
        userprovidersss:
          dal:
            dao: debug
