spring:
  datasource:
    url: jdbc:mysql://39.107.34.150:3306/mymart?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 1
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,config
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
  redisson:
    address: 39.107.34.150:6379
    timeout: 3000
    database: 0
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 3000
      min-idle: 4
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql


dubbo:
  application:
    name: mart-service
    owner: dylan
  protocol:
    name: dubbo
    port: 20881
  registry:
    address: zookeeper://39.107.34.150:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://39.107.34.150:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.dylan.martprovider
server:
  port: 8062
logging:
  level:
    com:
      dylan:
        userprovidersss:
          dal:
            dao: debug
